
FROM golang:1.23 AS builder


WORKDIR /app


COPY go.mod go.sum ./
RUN go mod tidy


COPY . .


RUN CGO_ENABLED=0 go build -o jwt-auth-app main.go



FROM alpine:latest


RUN apk --no-cache add ca-certificates


WORKDIR /root/

COPY .env .  



COPY --from=builder /app/jwt-auth-app .


EXPOSE 8002


CMD ["./jwt-auth-app"]
